<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Tasklabe.GitHub.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tasklabe.Core\Tasklabe.Core.csproj" />
  </ItemGroup>
</Project>
